### ISSUE TITLE
User can view articles from the NYT archives for a specific topic.

### ISSUE THREAD

**Issue by jjnotjayjay** [jjnotjayjay/news-hunter#1]
# Motivation
The user of the app may not be interested in the plethora of news stories out there, so will likely want to limit the articles they see to a topic of interest.

# Tasks
- [x] Initialize project with create-react-app; remove unnecessary boilerplate.
- [x] Add a SearchQuery component containing a text input box for user to specify the query topic and a button to submit the query.
- [x] Store the value of the text input box in SearchQuery state and update state on value change.
- [x] Using `axios`, clicking on the `submit` button should send a GET request to the NYT API.
- [x] Render the returned set of articles as simple text.
- [x] Articles with multimedia should render a thumbnail; articles without should render a placeholder image.
- [x] Added background image using `styled-components` as a dependency, as is the Acorns way.
- [x] Add styled title to page.
- [x] Add styled subtitle to page.
- [x] Improve styling of the text input and submit buttons.
- [x] Improve styling of the articles.
