### ISSUE TITLE
Improve app usability and cross browser compatibility; deploy to Github pages.

### ISSUE THREAD

**Issue by jjnotjayjay** [jjnotjayjay/news-hunter#3]
# Motivation
To make the app more natural and ensure it displays properly on multiple browsers, and then to deploy it live to Github pages for easy access.

# Tasks
- [x] Increase rem measurements by a factor of 1.5 throughout app.
- [x] Pushing 'Enter' should submit the search query.
- [x] Clicking the entire card should link to the article; link should be removed.
- [x] Implement cross-browser styling for transitions and transforms.
- [x] Add in antialiasing for OSX Chrome, Safari and Firefox.
- [x] Test styling in multiple browsers with BrowserStack.
- [x] Deploy the app to Github Pages.
- [x] Add GIFs and deployment link to the readme.
